node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git branch: 'geocat_develop', url: 'https://github.com/geoadmin/geocat.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'M3'
   }
   stage('Build') {
       withEnv(['MAVEN_OPTS=-Xmx512M -XX:MaxPermSize=256M']) {
           sh "'${mvnHome}/bin/mvn' -DskipTests -Dmaven.test.failure.ignore clean package"
        }
   }
   stage('Archive') {
       archiveArtifacts artifacts: '**/target/*.war', fingerprint: true 
  } 
}
