package org.fao.geonet.repository;

import org.fao.geonet.domain.SchematronCriteria;

/**
 * Implementation for all {@link SchematronCriteria} queries that cannot be
 * automatically generated by Spring-data.
 * 
 * @author delawen
 */
public class SchematronCriteriaRepositoryImpl implements SchematronCriteriaRepositoryCustom {
	
}
