package org.fao.geonet.repository;

import org.fao.geonet.domain.Schematron;

/**
 * Implementation for all {@link Schematron} queries that cannot be
 * automatically generated by Spring-data.
 * 
 * @author delawen
 */
public class SchematronRepositoryImpl implements SchematronRepositoryCustom {
	
}
